### ISSUE TITLE
ModuleNotFoundError: No module named 'eval_utils'

### ISSUE THREAD

**Issue by han9979** [zhengzhi-1997/Drug_Package_Generation#1]
你好，请问我在复现代码的时候，遇到 ModuleNotFoundError: No module named 'eval_utils' 这个问题，好久都没解决，请问这个问题该如何解决呀？谢谢呀！

**Comment by zhengzhi-1997** [comment]
eval_utils.py是一个空的py文件，整理的时候被我删掉了，已经修改了此bug

**Comment by han9979** [comment]
谢谢修改啦，现在在运行 python run_simple.py --reinforce no 时遇到了FileNotFoundError: [Errno 2] No such file or directory: 'I:\\drug_package_generation/data/MIMIC/dataset/dict/drug_dict.dict' 这个错，请问dataset这个文档在哪里呢？除了MIMIC需要自己下载还需要再准备哪些数据集呢？
















在 2022-08-24 22:03:19，"zhengzhi-1997" ***@***.***> 写道：

eval_utils.py是一个空的py文件，整理的时候被我删掉了，已经修改了此bug

**Comment by zhengzhi-1997** [comment]
请查看readme
