### ISSUE TITLE
生成空文件夹

### ISSUE THREAD

**Issue by han9979** [zhengzhi-1997/Drug_Package_Generation#2]
您好，我在运行python run_simple.py --reinforce no这句命令的时候，产生这样一个错，FileNotFoundError: [Errno 2] No such file or directory: 'I:/Drug_Package_Generation-main/code/DPRTrans/MIMIC/DPG/results/models/MLE_0.001.pkl' ，生成的文件夹是空的，请问这是什么情况呀

**Comment by zhengzhi-1997** [comment]
请查看parser参数含义备注，指定参数为训练模式

**Comment by unu165** [comment]
请问可以发一下数据集吗
